name = "tg-lottery-bot"
main = "src/index.js"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

# KV namespace 会由 GitHub Actions 自动创建并写入
[[kv_namespaces]]
binding = "LOTTERY_KV"
id = "f21881ccbcfc44cdb0dc004e5fa94631"
preview_id = "f21881ccbcfc44cdb0dc004e5fa94631"
